"""empty message

Revision ID: 8f1d47850b45
Revises: 705b439f61a4
Create Date: 2019-05-25 15:20:02.542309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f1d47850b45'
down_revision = '705b439f61a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('slug', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
