"""empty message

Revision ID: 9cf4cb1819d8
Revises: aee103e070c7
Create Date: 2019-05-25 21:44:56.190495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9cf4cb1819d8'
down_revision = 'aee103e070c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('test', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
