"""empty message

Revision ID: aee103e070c7
Revises: cedafc365a71
Create Date: 2019-05-25 15:36:04.068931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aee103e070c7'
down_revision = 'cedafc365a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('slug', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
